version: 2

sources:
  - name: staging
    database: bigqueryzoomcampde
    schema: trip_data_all
    tables:
      - name:  green_tripdata
      - name: yellow_tripdata
      - name: fhv_data_table
